### ISSUE TITLE
Instructions don't work

### ISSUE THREAD

**Issue by 8enmann** [Melissa-AI/Melisandre#4]
```
$ FLASK_APP=main.py flask run
Usage: flask run [OPTIONS]

Error: The file/path provided (main) does not appear to exist.  Please verify the path is correct.  If app is not on PYTHONPATH, ensure the extension is .py
```
Tried with both python 2.7 and 3.6 on OSX. Also tried absolute path:
```
$ FLASK_APP=`pwd`/main.py flask run
```
Same error

**Comment by tanay1337** [comment]
@8enmann thank you for your patience! This issue has been fixed here: https://github.com/Melissa-AI/Melisandre/commit/0f8ebb07585b835bdcf28d3ed6bae545e6552f73

For more details on the issue, please refer to this discussion: https://groups.google.com/forum/#!topic/melissa-support--discussion-forum/kM21TrUAN9U
